### ISSUE TITLE
我看现在图片发送不了  这个怎么弄

### ISSUE THREAD

**Issue by maibou8888** [xiaoqing91/ChatAppForMacOS#1]

**Comment by hanxiaoqing19910916** [comment]
没做这一块的功能 这个仅仅是一个本地的聊天界面练习demo~~

**Comment by maibou8888** [comment]
当发很多中文的时候message的对话框显示不全,这个应该怎么办   比如:  室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方南克办公室方脑壳南克办公室方脑壳脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳伯南克办公室方脑壳

**Comment by hanxiaoqing19910916** [comment]
请问你们做什么mac软件呢？ 我这个demo只作为初学mac的熟悉api的练手项目，应用到实践中还差得远。

**Comment by maibou8888** [comment]
是的   就是刚才看的时候发现发送一条文本包含很多中文的时候框框显示不全

**Comment by hanxiaoqing19910916** [comment]
你们在做mac端的即时通讯软件？

**Comment by maibou8888** [comment]
是的

**Comment by maibou8888** [comment]
现在发一些字符还好  就是发很多中文的时候那个框框显示不全  就比如我上面给你发的那么多文字

**Comment by hanxiaoqing19910916** [comment]
@maibou8888 已解决输入文字过多问题，具体方法看commit

**Comment by hanxiaoqing19910916** [comment]
@maibou8888 你在什么公司，现在做mac即时通讯的不多哇

**Comment by hanxiaoqing19910916** [comment]
@maibou8888  这个工程我打算从github移除了，你若遇到mac技术问题直接加我qq，咱们一起讨论解决吧 190658047

**Comment by Johankoi** [comment]
> @maibou8888 这个工程我打算从github移除了，你若遇到mac技术问题直接加我qq，咱们一起讨论解决吧 190658047

delete
